export const navData = [
  { name: "HOME", id: "home", type: "scroll" },
  { name: "OUR MENU", id: "OURMENU", type: "dropdown" },
  { name: "BLOG", id: "BLOG", type: "scroll" },
  { name: "RSPV", id: "RSPV", type: "scroll" },
  {
    name: "INSTAGRAM",
    id: "https://instagram.com",
    type: "icon",
    icon: "instagram",
  },
  {
    name: "WHATSAPP",
    id: "https://wa.me/123456789",
    type: "icon",
    icon: "whatsapp",
  },
];
export const ourMenuItems = [
  "Main menu",
  "Rice Bowl",
  "Noodle and Pasta",
  "PIZZA",
  "Dessert",
  "Bites",
  "Coffe Based",
  "KINI Signature",
  "Coffe Mocktail",
  "Flavored tea",
  "Milk Shake",
  "Fancy Mocktail",
  "Juice",
  "Powder Based",
  "Mineral Water",
];
// data review
export const testimonial = [
  {
    title: "Proyek Pembangunan Perumahan",
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    title: "Gedung Perkantoran Komersial",
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    title: "Renovasi Ruang Ritel",
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    title: "Konstruksi Gudang Industri",
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    title: "Restorasi Bangunan Bersejarah",
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    title: "Educational Facility Expansion",
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol`,
    note: "Note: Max. 380 Character",
  },
];
